name: 🚀 Deploy para InfinityFree

on:
  push:
    branches:
      - main  # Ou a sua branch principal

jobs:
  web-deploy:
    name: 🎉 Deploy via FTP
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Pegando o código atual
        uses: actions/checkout@v4

      - name: 📂 Sincronizando arquivos
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /htdocs/  # Pasta raiz do InfinityFree
